# Generated by Django 4.1.7 on 2023-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0002_alter_business_cafeid_alter_business_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="neighborhood",
            new_name="district",
        ),
        migrations.AddField(
            model_name="business",
            name="image",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
