# Generated by Django 4.1.7 on 2023-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="cafeId",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
