# Generated by Django 5.0 on 2024-01-02 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="owner",
        ),
        migrations.RenameField(
            model_name="availability",
            old_name="available_tables",
            new_name="total_tables",
        ),
        migrations.AddField(
            model_name="availability",
            name="booked_tables",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="business",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="business_reviews", to="business.review"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BusinessOwner",
        ),
    ]
